robot_reach_study_node:
  ros__parameters:

    # moveit stuff
    planning_group: "manipulator"
    fixed_frame: "base_link"
    object_frame: "reach_object"
    tool_frame: "tcp"

    # pcd stuff
    pcd_package: "reach_demo"
    pcd_filename_path: "config/part.pcd"

    # average neighbor calc
    get_avg_neighbor_count: false

    # db comparison
    compare_dbs: [ "" ]

    # database stuff
    config_name: "demo_config"
    results_package: "reach_demo"
    results_directory: "results"

    # to do path generation or not
    generate_paths: true

    visualize_results: true
    keep_running: true
    run_initial_study_only: false

    optimization:
      radius: 0.2
      max_steps: 10
      step_improvement_threshold: 0.01

    ik_solver_config:
      name: "moveit_reach_plugins/ik/MoveItIKSolver"
      tool_frame: "tcp"
      distance_threshold: 0.0
      planning_group: "manipulator"
      collision_mesh_package: "package://reach_demo/config/part.ply"
      collision_mesh_filename_path: "config/part.ply"
      collision_mesh_frame: "reach_object"
      touch_links: [""]
      evaluation_plugin:
        name: "reach_core/plugins/MultiplicativeFactory"
        plugins: ["moveit_reach_plugins/evaluation/ManipulabilityMoveIt", "moveit_reach_plugins/evaluation/DistancePenaltyMoveIt"]
        moveit_reach_plugins/evaluation/ManipulabilityMoveIt:
          planning_group: "manipulator"
        moveit_reach_plugins/evaluation/DistancePenaltyMoveIt:
          planning_group: "manipulator"
          distance_threshold: 0.025
          exponent: 2
          collision_mesh_package: "package://reach_demo/config/part.ply"
          collision_mesh_filename_path: "config/part.ply"
          collision_mesh_frame: "reach_object"
          touch_links: [""]

    display_config:
      name: "moveit_reach_plugins/display/MoveItReachDisplay"
      planning_group: "manipulator"
      collision_mesh_package: "package://reach_demo/config/part.ply"
      collision_mesh_filename_path: "config/part.ply"
      collision_mesh_frame: "reach_object"
      fixed_frame: "base_link"
      marker_scale: 0.05

    path_generation_config:

      # one planning group for all path generation plugins
      planning_group: "manipulator"
      fixed_frame: "base_link"

      # initial sources are mutually exclusive
      initial_source_db: true     # false
      db:
        config_name: "demo_config"
        package: "reach_demo"
        directory: "results"
        name: "optimized_reach.db"

      initial_source_robot_configurations: false  # true
      robot_configurations:
        name: "source.yaml"
        package: "reach_demo"
        directory: "config"

      collision_mesh_package: "package://reach_demo/config/part.ply"
      collision_mesh_frame: "reach_object"

      path_plugins:
        - path_1
#        - path_2
#        - path_3
#        - path_4

      path_1:
        plugin_name: "moveit_reach_plugins/path_generation/CartesianPath"
        ##########################################################
        ############# PATH PLANNING SPECIFIC PARAMS ##############
        #########################################################
        max_velocity_scaling_factor: 0.5
        max_acceleration_scaling_factor: 0.5
        tool_frame: "tcp"
        max_eef_step: 0.005
        jump_threshold: 0.1 # cca 5 degrees
        #########################################################
        distance_threshold: 0.0 # distance threshold for collision checking
        global_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        tool_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg

      path_2:
        plugin_name: "moveit_reach_plugins/path_generation/PlannerPath"

      path_3:
        plugin_name: "moveit_reach_plugins/path_generation/PlannerPath"

      path_4:
        plugin_name: "moveit_reach_plugins/path_generation/CartesianPath"
        global_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        tool_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0   #deg
          rz: 0.0    #deg
